import "./globals.css";
import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Mypage/Header";
import Navigation from "./components/Navigation";

const source_code_pro = Source_Code_Pro({
  // 後ほどTailwindCSSで指定する変数名を指定する
  variable: "--font-source-code-pro",
  // 利用したいweightやstyleなど指定する
  weight: "400",
  style: "normal",
  // サブセット
  subsets: ["latin"],
  // 代替フォントを表示する
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-back">
        <div className="">
          <Navigation />
          <main className="text-text flex-1 max-w-4xl w-full mx-auto px-8 pt-8">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
